[AAE-13781] Set ENVIRONMENT_FORCE_SINGLE_REPOSITORY_URL variable
Alfresco/alfresco-process-infrastructure-deployment pull request #1122
Opened 2023-04-17 13:27 UTC by pmartinezga

https://alfresco.atlassian.net/browse/AAE-13781

2023-04-17 14:54 UTC, mteodori requested changes

2023-04-17 14:54 UTC, mteodori commented on helm/alfresco-process-infrastructure/values.yaml
> +    force-single-repository-url: false
this should be `force` to match where it is used, should we keep `force-single-repository-url` better match other vars and use CamelCase `forceSingleRepositoryUrl`

2023-04-17 19:41 UTC, andrea-ligios approved these changes
LGTM!

2023-04-19 08:35 UTC, gicappa approved these changes
LGTM

2023-04-19 10:08 UTC, closed without merging